/* 
    Author: António Malato
    This is a header file for the web app to configure the tractor settings and view the tractor status

    If a change is made add the day and the title of the change here:

    24/6/2026 - Initial creation of the file
    05/7/2026 - Added the start webserver function


*/

#ifndef WEB_APP_H
#define WEB_APP_H

#include "common.h"

extern web_cmds_t web_page_received_settings_data_snapshot;
extern web_data_t web_data_to_send_snapshot;


static const char index_html[] = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Tractor Settings and Data</title>\n"
"\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, Helvetica, sans-serif;\n"
"            background: #f5f5f5;\n"
"            margin: 40px;\n"
"        }\n"
"\n"
"        .container {\n"
"            max-width: 700px;\n"
"            margin: auto;\n"
"        }\n"
"\n"
"        .card {\n"
"            background: white;\n"
"            padding: 20px;\n"
"            margin-bottom: 20px;\n"
"            border-radius: 10px;\n"
"            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);\n"
"        }\n"
"\n"
"        h2 {\n"
"            margin-top: 0;\n"
"            color: #2c3e50;\n"
"        }\n"
"\n"
"        table {\n"
"            width: 100%;\n"
"            border-collapse: collapse;\n"
"        }\n"
"\n"
"        td {\n"
"            padding: 10px 5px;\n"
"        }\n"
"\n"
"        input[type=\"text\"],\n"
"        input[type=\"number\"] {\n"
"            width: 100%;\n"
"            padding: 8px;\n"
"            box-sizing: border-box;\n"
"        }\n"
"\n"
"        .readonly {\n"
"            background: #ececec;\n"
"        }\n"
"\n"
"        .switch {\n"
"            position: relative;\n"
"            display: inline-block;\n"
"            width: 60px;\n"
"            height: 34px;\n"
"        }\n"
"\n"
"        .switch input {\n"
"            opacity: 0;\n"
"            width: 0;\n"
"            height: 0;\n"
"        }\n"
"\n"
"        .slider {\n"
"            position: absolute;\n"
"            cursor: pointer;\n"
"            top: 0;\n"
"            left: 0;\n"
"            right: 0;\n"
"            bottom: 0;\n"
"            background: #ccc;\n"
"            transition: .3s;\n"
"            border-radius: 34px;\n"
"        }\n"
"\n"
"        .slider:before {\n"
"            position: absolute;\n"
"            content: \"\";\n"
"            height: 26px;\n"
"            width: 26px;\n"
"            left: 4px;\n"
"            bottom: 4px;\n"
"            background: white;\n"
"            transition: .3s;\n"
"            border-radius: 50%;\n"
"        }\n"
"\n"
"        input:checked+.slider {\n"
"            background: #4CAF50;\n"
"        }\n"
"\n"
"        input:checked+.slider:before {\n"
"            transform: translateX(26px);\n"
"        }\n"
"\n"
"        .led {\n"
"            width: 20px;\n"
"            height: 20px;\n"
"            border-radius: 50%;\n"
"            border: 2px solid #444;\n"
"            display: inline-block;\n"
"            transition: 0.3s;\n"
"        }\n"
"\n"
"        /* OFF */\n"
"        .led.off {\n"
"            background: #b00000;\n"
"            box-shadow: 0 0 5px #500;\n"
"        }\n"
"\n"
"        /* ON */\n"
"        .led.on {\n"
"            background: #00ff00;\n"
"            box-shadow:\n"
"                0 0 8px #00ff00,\n"
"                0 0 15px #00ff00,\n"
"                0 0 25px #00ff00;\n"
"        }\n"
"    </style>\n"
"\n"
"</head>\n"
"\n"
"<body>\n"
"    <div class=\"header\">\n"
"        <h1>Tractor Settings and Data</h1>\n"
"    </div>\n"
"\n"
"    <div class=\"container\">\n"
"\n"
"        <div class=\"card\">\n"
"            <h2>Outputs</h2>\n"
"\n"
"            <table>\n"
"\n"
"                <tr>\n"
"                    <td>Plant Mode Status</td>\n"
"\n"
"                    <td>\n"
"                        <div id=\"activeLED\" class=\"led off\"></div>\n"
"                    </td>\n"
"\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Number of Planted Seeds/Trees</td>\n"
"                    <td><input class=\"readonly\" id=\"numPlanted\" type=\"text\" value=\"0\" readonly></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Accumulated Distance</td>\n"
"                    <td><input class=\"readonly\" id=\"accDistance\" type=\"text\" value=\"0\" readonly></td>\n"
"                </tr>\n"
"\n"
"            </table>\n"
"        </div>\n"
"\n"
"        <div class=\"card\">\n"
"            <h2>GPS Data</h2>\n"
"\n"
"            <table>\n"
"\n"
"                <tr>\n"
"                    <td>Latitude</td>\n"
"                    <td><input class=\"readonly\" id=\"latitude\" type=\"text\" value=\"0.000000\" readonly></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Longitude</td>\n"
"                    <td><input class=\"readonly\" id=\"longitude\" type=\"text\" value=\"0.000000\" readonly></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Altitude (m)</td>\n"
"                    <td><input class=\"readonly\" id=\"altitude\" type=\"text\" value=\"0.0\" readonly></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>HDOP</td>\n"
"                    <td><input class=\"readonly\" id=\"hdop\" type=\"text\" value=\"0.0\" readonly></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Satellite Number</td>\n"
"                    <td><input class=\"readonly\" id=\"satellites\" type=\"text\" value=\"0\" readonly></td>\n"
"                </tr>\n"
"\n"
"            </table>\n"
"        </div>\n"
"\n"
"        <div class=\"card\">\n"
"            <h2>Configuration Inputs</h2>\n"
"\n"
"            <table>\n"
"\n"
"                <tr>\n"
"                    <td>Distance between plants</td>\n"
"                    <td><input id=\"deltaPosition\" type=\"number\" min=\"0\" max=\"255\" value=\"10\"></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Plant Time (s)</td>\n"
"                    <td><input id=\"plantTime\" type=\"number\" min=\"0\" max=\"255\" value=\"2\"></td>\n"
"                </tr>\n"
"\n"
"                <tr>\n"
"                    <td>Reset</td>\n"
"                    <td>\n"
"                        <label class=\"switch\">\n"
"                            <input id=\"resetToggle\" type=\"checkbox\">\n"
"                            <span class=\"slider\"></span>\n"
"                        </label>\n"
"                    </td>\n"
"                </tr>\n"
"                <tr>\n"
"                    <td colspan=\"2\" style=\"text-align:right;\">\n"
"\n"
"                        <button onclick=\"send_input_data_to_server()\">\n"
"                            SEND\n"
"                        </button>\n"
"\n"
"                    </td>\n"
"                </tr>\n"
"\n"
"\n"
"            </table>\n"
"\n"
"        </div>\n"
"\n"
"    </div>\n"
"\n"
"    <script>\n"
"\n"
"        // Example update functions\n"
"\n"
"        function setPlantingsDistanceAndTotal(totalPlantings, accDistance) {\n"
"            document.getElementById(\"numPlanted\").value = totalPlantings;\n"
"            document.getElementById(\"accDistance\").value = accDistance;\n"
"        }\n"
"\n"
"        function setActive(active) {\n"
"            const led = document.getElementById(\"activeLED\");\n"
"\n"
"            if (active) {\n"
"                led.classList.remove(\"off\");\n"
"                led.classList.add(\"on\");\n"
"            }\n"
"            else {\n"
"                led.classList.remove(\"on\");\n"
"                led.classList.add(\"off\");\n"
"            }\n"
"        }\n"
"        function setGPS(lat, lon, alt, hdop, sats) {\n"
"            document.getElementById(\"latitude\").value = lat.toFixed(6);\n"
"            document.getElementById(\"longitude\").value = lon.toFixed(6);\n"
"            document.getElementById(\"altitude\").value = alt.toFixed(2);\n"
"            document.getElementById(\"hdop\").value = hdop.toFixed(2);\n"
"            document.getElementById(\"satellites\").value = sats;\n"
"        }\n"
"\n"
"        // Read configuration values\n"
"        function getConfiguration() {\n"
"            return {\n"
"                deltaPosition: Number(document.getElementById(\"deltaPosition\").value),\n"
"                plantTime: Number(document.getElementById(\"plantTime\").value),\n"
"                reset: document.getElementById(\"resetToggle\").checked\n"
"            };\n"
"        }\n"
"\n"
"        async function refresh() {\n"
"            try {\n"
"                const response = await fetch(\"/outputs\");\n"
"                if (!response.ok) {\n"
"                    return;\n"
"                }\n"
"\n"
"                const data = await response.json();\n"
"                setGPS(data.gps_data.lat, data.gps_data.lon, data.gps_data.alt, data.gps_data.hdop, data.gps_data.sat);\n"
"                setActive(data.plant_mode_active);\n"
"                setPlantingsDistanceAndTotal(data.totalPlantings, data.acc_distance);\n"
"\n"
"            } catch (err) {\n"
"\n"
"                console.log(err);\n"
"            }\n"
"\n"
"\n"
"        }\n"
"\n"
"        async function send_input_data_to_server() {\n"
"            const data = getConfiguration();\n"
"            await fetch(\"/inputs\", {\n"
"\n"
"                method: \"POST\",\n"
"\n"
"                headers: {\n"
"                    \"Content-Type\": \"application/json\"\n"
"                },\n"
"\n"
"                body: JSON.stringify(data)\n"
"\n"
"            });\n"
"        }\n"
"        // Start updating after window finishes loading\n"
"        window.onload = function () {\n"
"            refresh();\n"
"\n"
"            setInterval(refresh, 500);\n"
"        };\n"
"    </script>\n"
"\n"
"</body>\n"
"\n"
"</html>";



httpd_handle_t start_webserver();

// JSON Functions




#endif /* WEB_APP_H */